site_name: Julius Bot

site_url: https://io-deepsea/julius-docs
theme:
  name: material
  palette:
    primary: deep purple  # Cozy/Chill vibe
    accent: pink
  icon:
    repo: fontawesome/brands/github

nav:
  - Início: index.md
  - Instalação: installation.md
  - Comandos: commands.md